name: Windows Build
on:
  push:
    branches: [ dev ]
    tags:
      - v*
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-2017
    if: ${{ startsWith(github.ref, 'refs/tags') || !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: | 
        git submodule init
        git submodule update

    - name: Build zlib
      run: |
         git clone https://github.com/madler/zlib.git
         md zlib-build
         cd zlib-build
         cmake ..\zlib -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="..\zlib-install"
         cmake --build . --config Release --target install
         cd ..
         dir
  
    - name: Build ITK
      run: |
        md ITK-build
        cd ITK-build
        cmake.exe -G "Visual Studio 15 2017" -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=Release ..\ITK
        cmake --build . --config Release --target Install
        cd ..
      shell: cmd
         

    - name: Build samseg python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        architecture: 'x64'
    - run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py bdist_wheel
        python -m pip install samseg -f .\dist\
        python -c 'import samseg'
        rm samseg\*.pyd
        rm samseg\Release\*.pyd
      env:
        ZLIB_INCLUDE_DIR: .\zlib-install\include
        ZLIB_LIBRARY: .\zlib-install\lib\zlibstatic.lib

    - name: Build samseg python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py bdist_wheel
        python -m pip install samseg -f .\dist\
        python -c 'import samseg'
        rm samseg\*.pyd
        rm samseg\Release\*.pyd
      env:
        ZLIB_INCLUDE_DIR: .\zlib-install\include
        ZLIB_LIBRARY: .\zlib-install\lib\zlibstatic.lib

    - name: Build samseg python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py bdist_wheel
        python -m pip install samseg -f .\dist\
        python -c 'import samseg'
        rm samseg\*.pyd
        rm samseg\Release\*.pyd
      env:
        ZLIB_INCLUDE_DIR: .\zlib-install\include
        ZLIB_LIBRARY: .\zlib-install\lib\zlibstatic.lib
        
    - name: Build samseg python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'
    - run: |
        python -m pip install --user --upgrade setuptools wheel
        python setup.py bdist_wheel
        python -m pip install samseg -f .\dist\
        python -c 'import samseg'
        rm samseg\*.pyd
        rm samseg\Release\*.pyd
      env:
        ZLIB_INCLUDE_DIR: .\zlib-install\include
        ZLIB_LIBRARY: .\zlib-install\lib\zlibstatic.lib

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-wheels
        path: .\dist\*.whl

    - name: Upload to PyPI
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
      run: |
        python -m pip install twine
        python -m twine upload .\dist\*.whl -u __token__ -p "$env:PASSWORD"
      env:
        PASSWORD: ${{ secrets.PYPI_TOKEN }}
